### ISSUE TITLE
Tools (links)

### ISSUE THREAD

**Issue by niizom** [AlexMatusevich/pm-ba#6]

**Comment by tkosheleva** [comment]
- [x] make newlines for "Goal" and "Outcome"

Development
At this stage, the actual development starts. It’s important that every developer sticks to the agreed blueprint. Also, make sure you have proper guidelines in place about the code style and practices.
**Goal:** Translate the design of the system into code. 
**Outcome:** testable, functional software, and a Source Code Document.

Deployment At this stage, the goal is to deploy the software to the production environment so users can start using the product. However, many organisations choose to move the product through different deployment environments such as a testing or staging environment. This allows any stakeholders to safely play with the product before releasing it to the market. Besides, this allows any final mistakes to be caught before releasing the product.
**Goal:** Software delivery to a target device. 
**Outcome:** Fully operational software in a live environment.
