### ISSUE TITLE
Integration management

### ISSUE THREAD

**Issue by niizom** [AlexMatusevich/pm-ba#8]

**Comment by tkosheleva** [comment]
- [x] make bold style

**Develop Project Charter**—The process of developing a document that formally authorizes the existence of a project and provides the project manager with the authority to apply organizational resources to project activities.
**Develop Project Management Plan**—The process of defining, preparing, and coordinating all plan components and consolidating them into an integrated project management plan.
**Direct and Manage Project Work**—The process of leading and performing the work defined in the project management plan and implementing approved changes to achieve the project’s objectives.
**Manage Project Knowledge**—The process of using existing knowledge and creating new knowledge to achieve the project’s objectives and contribute to organizational learning.
**Monitor and Control Project Work**—The process of tracking, reviewing, and reporting overall progress to meet the performance objectives defined in the project management plan.
**Perform Integrated Change Control**—The process of reviewing all change requests; approving changes and managing changes to deliverables, organizational process assets, project documents, and the project management plan; and communicating the decisions.
**Close Project or Phase**—The process of finalizing all activities for the project, phase, or contract.
